import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
const inter = Inter({ subsets: ["latin"] });
 
import { ChakraProvider } from '@chakra-ui/react'
 

export const metadata: Metadata = {
  title: "Apprecial",
  description: "Generated by Apprecial",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans" >
      <head>
      <link
      href="https://api.fontshare.com/v2/css?f[]=satoshi@900,700,500,300,400&display=swap"
      rel="stylesheet"
    />
      </head>
      <body className="font-sans">
        <div className="overflow-hidden">
          <ChakraProvider>
            {children}
          </ChakraProvider>
        </div>
      </body>
    </html>
  );
}
