import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
const inter = Inter({ subsets: ["latin"] });
import '@/app/fonts/css/satoshi.css'
import { ChakraProvider } from '@chakra-ui/react'
const satoshi = localFont({ src: './fonts/Satoshi-Variable.woff2' })

export const metadata: Metadata = {
  title: "Apprecial",
  description: "Generated by Apprecial",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={satoshi.className}>
      <body>
        <div className="overflow-hidden">
          <ChakraProvider>
            {children}
          </ChakraProvider>
        </div>
      </body>
    </html>
  );
}
